version: "2.1"
services:
  dhcp:
    image: networkboot/dhcpd
    container_name: r2-dhcp
    volumes:
      - ../config/dhcp:/data
    network_mode: host
    command:
      - ${DHCP_PORT}

  tftp:
    image: pghalliday/tftp
    container_name: r2-tftp
    volumes:
      - ${TFTP_DIR}:/var/tftpboot
    ports:
      - "69:69/udp" 
      
  nfs_v3:
    image: erichough/nfs-server:latest
    container_name: r2-nfs-v3
    privileged: true
    volumes:
      - ${NFS_SHARE_DIR}:/data
      - ../config/nfs/exports:/etc/exports
    ports:
      - "2049:2049/tcp"
      - "2049:2049/udp"
      - "111:111/tcp"
      - "111:111/udp"
      - "32765:32765/tcp" 
      - "32765:32765/udp"
      - "32767:32767/tcp" 
      - "32767:32767/udp"
